rollout_step: 1
variant_name: K1-Unet_medium_nearest-baseline
parent_variant: null
model_architecture: UNet_medium_nearest

learning_rate: 0.001
epochs: 2
lr_scheduler_patience: 200
early_stop_patience: 200

