rollout_step: 3
variant_name: K3-Unet_medium-only_div_001-drop
parent_variant: K2-Unet_medium-only_div_001-drop


learning_rate: 0.0005
epochs: 9
lr_scheduler_patience: 2
early_stop_patience: 5
dropout: 0.15
