models:
  folder: "./data/onnx"
  default_index: 0

simulation:
  fps: 15.0
  grid_resolution: 128

engine:
  window_width: 800
  window_height: 800
  vsync: false
  onnx_providers:
    - "CPUExecutionProvider"
    - "CUDAExecutionProvider"
  gpu_enabled: true