general_config:
  grid_resolution: 128
  onnx_model_path: "./data/onnx/SmallUnet.onnx"

simulation:
  grid_resolution: [128, 128, 1]

engine:
  window_width: 1280
  window_height: 720
  onnx_providers:
    - "CPUExecutionProvider"
    - "CUDAExecutionProvider"
  gpu_enabled: true