vdb_tools:
  blender_cache_directory: "./data/blender_caches"
  npz_output_directory: "./data/npz"
  stats_percentiles: [75, 90, 95, 99, 100]
  normalization_percentile: 100
  stats_output_file: "data/_field_stats.yaml"

models:
  pytorch_folder: "./data/checkpoints/"
  onnx_folder: "./data/onnx-export"
  default_index: 0

simulation:
  fps: 24.0
  grid_resolution: 128
  input_channels: 6      #[density, velx, vely, density-1, emitter_mask, collider_mask]

engine:
  window_width: 1250
  window_height: 820
  onnx_providers:
    - "CPUExecutionProvider"
    - "CUDAExecutionProvider"
  gpu_enabled: true