models:
  folder: "./data/onnx"
  default_index: 0

simulation:
  fps: 30.0
  grid_resolution: 128

engine:
  window_width: 1280
  window_height: 720
  vsync: false
  onnx_providers:
    - "CPUExecutionProvider"
    - "CUDAExecutionProvider"
  gpu_enabled: true