models:
  folder: "./data/onnx"
  default_index: 0

simulation:
  fps: 15.0
  grid_resolution: 128
  input_channels: 4      #[density, velx, vely, density-1]

engine:
  window_width: 1050
  window_height: 820
  onnx_providers:
    - "CPUExecutionProvider"
    - "CUDAExecutionProvider"
  gpu_enabled: true