rollout_step: 1
variant_name: simple-Unet_medium-only_div
parent_variant: null
model_architecture: UNet_medium

learning_rate: 0.001
epochs: 10
lr_scheduler_patience: 2
early_stop_patience: 5

physics_loss:
  mse_weight: 1.0
  divergence_weight: 0.01
  enable_divergence: true
  enable_gradient: false
  enable_emitter: false

