rollout_step: 4
variant_name: K4-Unet_medium-only_div_001-emit_001
parent_variant: K3-Unet_medium-only_div_001


learning_rate: 0.0005
epochs: 20
lr_scheduler_patience: 4
early_stop_patience: 10


physics_loss:
  mse_weight: 1.0
  divergence_weight: 0.01
  emitter_weight: 0.01
  enable_divergence: true
  enable_gradient: false
  enable_emitter: true