rollout_step: 1
parent_variant: null
variant_name: K1-Unet_small-medium-only_div_001

model_architecture: UNet_small-medium

learning_rate: 0.001
epochs: 10
lr_scheduler_patience: 2
early_stop_patience: 3

physics_loss:
  mse_weight: 1.0
  divergence_weight: 0.01
  enable_divergence: true
  enable_gradient: false
  enable_emitter: false

